members div
ion05/mun-website pull request #11
Opened 2021-04-30 13:22 UTC by yuvraajnarula

2021-04-30 17:44 UTC, ion05 requested changes

2021-04-30 17:44 UTC, ion05 commented on main.css
> +    z-index: 99;
```suggestion
    z-index: 99;
    position:fixed;
```

2021-04-30 17:44 UTC, ion05 commented on main.css
> +    font-family: "Ubuntu", sans-serif;
```suggestion
    font-family: "Antonio", sans-serif;
```

2021-04-30 17:44 UTC, ion05 commented on main.css
> +    left: -3%;
```suggestion
```

I will handle this

2021-04-30 17:47 UTC, yuvraajnarula commented on main.css
> +    font-family: "Ubuntu", sans-serif;
NO not happening already told you to keep maximum 3 fonts not more than that

2021-04-30 18:02 UTC, ion05 commented on main.css
> +    font-family: "Ubuntu", sans-serif;
We are using only 3 fonts.. nd this just adds more

2021-04-30 18:02 UTC, yuvraajnarula commented on main.css
> +    z-index: 99;
fixed-top added as a class no need to worry.

2021-04-30 18:04 UTC, ion05 commented on main.css
> +    font-family: "Ubuntu", sans-serif;
Antonio looks good on headings .. ubuntu is just bland

2021-04-30 18:06 UTC, ion05 commented on index.html
> +    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-4 " id="nav">
u didnt remove it

2021-04-30 18:08 UTC, yuvraajnarula commented on main.css
> +    font-family: "Ubuntu", sans-serif;
![image](https://user-images.githubusercontent.com/49155095/116736055-00398b00-aa0d-11eb-8ded-91ac9f31f854.png)
Antonio^
![image](https://user-images.githubusercontent.com/49155095/116736123-15161e80-aa0d-11eb-842d-ba9f50ea6fa4.png)
Ubuntu^

2021-04-30 18:13 UTC, ion05 commented on main.css
> +    font-family: "Ubuntu", sans-serif;
Yeah but Antonio looks good with all heading all caps. usse hi rakhle na

2021-04-30 18:21 UTC, ion05 commented on main.css
> +    font-family: "Ubuntu", sans-serif;
the first one aint antonio

2021-04-30 18:21 UTC, ion05 commented on main.css
> +    font-family: "Ubuntu", sans-serif;
u dlted the importing link for it

2021-05-01 09:38 UTC, ion05 requested changes
Combine Footer

2021-05-01 14:15 UTC, ion05 requested changes

2021-05-01 14:15 UTC, ion05 commented on index.html
> +            <p class="copyright">Amity International School Sec-46 © 2021</p>
```suggestion
            <p class="copyright">Amity International School Sector-46 © 2021</p>
```

2021-05-01 14:15 UTC, ion05 commented on index.html
> +                    <h4 style="text-align:left">We'd love to hear from you!</h4>
Switch fonts of Contact us and we'd love to hear

2021-05-01 14:19 UTC, merged