responsive
ion05/mun-website pull request #17
Opened 2021-05-19 18:34 UTC by yuvraajnarula

2021-05-20 06:04 UTC, ion05 requested changes

2021-05-20 06:04 UTC, ion05 commented on index.html
> +                            <a class="dropdown-item" href="#team"> Alumni</a>
Dont change all this

2021-05-20 06:04 UTC, ion05 commented
Why are you changing my internal links ? @yuvraajnarula

2021-05-20 07:01 UTC, yuvraajnarula commented
> Why are you changing my internal links ? @yuvraajnarula

coz one of them is wrong

2021-05-20 07:07 UTC, ion05 commented
> > Why are you changing my internal links ? @yuvraajnarula
> 
> coz one of them is wrong

All of them work properly and you have just removed all of them.

2021-05-20 17:37 UTC, ion05 commented
Dont mess with my links , they work fine.

2021-06-04 04:43 UTC, ion05 commented
Mere kuch changes not in this. Ek baar theek karke kar nd some dark things rehnde

2021-06-08 07:07 UTC, ion05 commented
![image](https://user-images.githubusercontent.com/49789627/121139244-2d702900-c856-11eb-9ea2-a32fa1cdf727.png)
fix this 
And the team section ko dark themed hi rehnde

2021-06-16 14:44 UTC, yuvraajnarula commented
There is a problem occurring with internal linking try adding it from your end

2021-06-16 14:46 UTC, ion05 commented
Kk, dont differenitate presidents and vice presidents sepereately

2021-06-16 14:47 UTC, yuvraajnarula commented
I think it would be better coz all mixed up doesnt look good

2021-06-21 06:54 UTC, merged